name: Run MusicDownload

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 拉代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装 ffmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: 安装依赖
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行脚本
  run: |
    python musicdownload.py